export function Footer() {
  return (
    <footer className="border-t border-white/10 py-8 text-center text-sm text-zinc-500">
      Generated by Nexora Audit Pro by Nexora Creation. No paid SEO data APIs used.
    </footer>
  )
}
