import Link from 'next/link'
import { listReports } from '@/features/audit/cache/auditCache'

export default async function DashboardPage() {
  const reports = await listReports()

  return (
    <main className="mx-auto min-h-[70vh] max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
      <h1 className="text-4xl font-black">Recent Reports</h1>
      <p className="mt-3 text-zinc-400">View recent website audit reports generated by Nexora Audit Pro.</p>
      <div className="mt-8 grid gap-4">
        {reports.length === 0 ? <div className="rounded-[10px] border border-white/10 bg-white/[0.04] p-8 text-zinc-400">No reports yet. Run your first website audit from the homepage.</div> : null}
        {reports.map((report) => (
          <Link key={report.id} href={`/report/${report.id}`} className="flex flex-col justify-between gap-3 rounded-[10px] border border-white/10 bg-white/[0.04] p-5 hover:border-yellow-300/40 md:flex-row md:items-center">
            <div>
              <div className="font-bold">{report.domain}</div>
              <div className="text-sm text-zinc-500">{report.finalUrl}</div>
            </div>
            <div className="text-2xl font-black text-nexora-yellow">{report.scores.overall}</div>
          </Link>
        ))}
      </div>
    </main>
  )
}
