import { NextResponse } from 'next/server'
import { jsPDF } from 'jspdf'
import { getReport } from '@/features/audit/cache/auditCache'

export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const report = await getReport(id)
  if (!report) return NextResponse.json({ error: 'Report not found.' }, { status: 404 })

  const doc = new jsPDF()
  doc.setFontSize(20)
  doc.text('Nexora Audit Pro', 20, 20)
  doc.setFontSize(12)
  doc.text(`Website: ${report.finalUrl}`, 20, 35)
  doc.text(`Audit date: ${new Date(report.createdAt).toLocaleString()}`, 20, 45)
  doc.text(`Overall score: ${report.scores.overall}/100`, 20, 55)
  doc.text('Top fixes:', 20, 70)
  report.summary.topFixes.slice(0, 5).forEach((fix, index) => {
    doc.text(`${index + 1}. ${fix.title}`, 24, 82 + index * 10)
  })
  doc.text('Generated by Nexora Audit Pro by Nexora Creation', 20, 280)

  const pdf = Buffer.from(doc.output('arraybuffer'))
  return new Response(pdf, {
    headers: {
      'content-type': 'application/pdf',
      'content-disposition': `attachment; filename="nexora-audit-${report.domain}.pdf"`
    }
  })
}
